### ISSUE TITLE
Implement separate Create-Edit modal for each page

### ISSUE THREAD

**Issue by horizech-admin** [horizech/levendr#1]
Don't rely on a standard Add Edit column modal for each case as it is causing problems.

**Comment by hamxa5155** [comment]
I have fixed the create edit modal. It takes account the select options from the props. Maybe we don't need to use a separater modal for each case now.

**Comment by jzorjnz** [comment]
@hamxa5155 makese sense. Let's keep it this way for now.
I am closing the issue.
